name: dev binary

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup go"
        uses: actions/setup-go@v4
      
      - name: "Build binary"
        run: |
          make

      - uses: actions/upload-artifact@v3
        with:
          name: vmihub-ubuntu
          path: bin/vmihub